name: Yachtie Firmware CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Elixir
      run: wget https://packages.erlang-solutions.com/erlang/debian/pool/elixir_1.10.4-1~ubuntu~focal_all.deb && sudo dpkg -i 'elixir_1.10.4-1~ubuntu~focal_all.deb'
    - name: Install hex
      run: mix local.hex --force
    - name: Install rebar
      run: mix local.rebar --force
    - name: Install nerves
      run: yes | mix archive.install hex nerves_bootstrap
      working-directory: yachtie-firmware
    - name: Install dependencies
      run: MIX_ENV=test mix deps.get --only test
      working-directory: yachtie-firmware
    - name: Check formatting
      run: mix format --check-formatted
      working-directory: yachtie-firmware
    - name: Run tests
      run: MIX_ENV=test mix test 
      working-directory: yachtie-firmware
